# GeminiTrader Configuration v6.5 - Phase 0 Initial Setup

# API Credentials - These should ideally be overridden by environment variables loaded in settings.py
api:
  binance_us:
    key: "YOUR_BINANCE_US_API_KEY" # Loaded from .env
    secret: "YOUR_BINANCE_US_SECRET" # Loaded from .env
  coinbase: # For Phase 2 DCA pipeline
    key: "YOUR_COINBASE_API_KEY" # Loaded from .env
    secret: "YOUR_COINBASE_API_SECRET" # Loaded from .env
  plaid: # For Phase 6 automated funding (Optional)
    client_id: "YOUR_PLAID_CLIENT_ID" # Loaded from .env
    secret: "YOUR_PLAID_SECRET" # Loaded from .env
    environment: "sandbox" # Or 'development', 'production'

# Trading Core Settings
trading:
  # General
  quote_asset: "USD" # Primary quote asset (adjust if using USDT, BUSD etc. on Binance.US)
  default_symbol_list: ["BTCUSD", "ETHUSD"] # Initial list of assets to consider (expand later)
  max_concurrent_symbols: 2 # How many symbols to actively trade simultaneously (Phase 6)

  # Geometric Grid Strategy (Phase 1+)
  grid:
    atr_period: 14 # Period for ATR calculation (e.g., 14 hours for 1h timeframe)
    atr_timeframe: '1h' # Timeframe for ATR calculation (e.g., 1h, 4h, 1d)
    spacing_factor: 0.5 # Multiplier for ATR to determine initial spacing from current price (e.g., 0.5 * ATR)
    geometric_factor: 1.618 # Factor by which spacing increases for subsequent levels (e.g., Fibonacci ratio)
    max_levels: 5 # Maximum number of buy orders in the grid
    base_order_size_usd: 10.0 # Base size for the first grid level in quote asset (USD)
    order_size_factor: 1.5 # Factor by which order size increases geometrically
    min_level_separation_pct: 0.002 # Minimum % separation between grid levels (prevents too-close orders)

  # Profit Taking (Phase 1/3+)
  profit_taking:
    # Simple TP (Phase 1)
    fixed_tp_percentage: 0.015 # 1.5% fixed target initially
    # Dynamic TP (Phase 3+)
    dynamic_tp_atr_multiple_min: 1.0 # Minimum ATR multiple for TP (low confidence)
    dynamic_tp_atr_multiple_max: 3.0 # Maximum ATR multiple for TP (high confidence)
    dynamic_tp_timeframe: '1h' # Timeframe for ATR used in dynamic TP

  # Risk Controls (Phase 3+)
  risk:
    max_total_position_usd_per_symbol: 1000.0 # Max total value allowed per symbol across all grid levels
    time_stop_enabled: true
    time_stop_duration_hours: 72 # How many hours a position can be open and stagnant/unprofitable before exit
    time_stop_profit_threshold: -0.005 # Exit if older than duration AND profit is below -0.5%
    confidence_floor_exit: 0.2 # Consider exiting if confidence drops below this threshold (needs more logic)
    portfolio_max_drawdown: 0.20 # Portfolio level stop % from peak equity (Phase 8) - Use with caution!

  # Dollar-Cost Averaging (DCA) (Phase 2+)
  dca:
    enabled: true
    schedule_day_1: 1 # e.g., 1st of the month
    schedule_day_2: 15 # e.g., 15th of the month
    schedule_time: "09:00" # Time to trigger DCA check (e.g., 9 AM local time)
    base_amount_usd: 50.0 # Default amount to DCA each time
    target_asset: "BTC" # Asset symbol (without quote, e.g., BTC, ETH) to buy with DCA funds
    funding_source: "Coinbase" # Or "Manual"
    auto_execute_pipeline: false # Set to true only after thorough testing of Phase 6

# Data Fetching & Caching
data:
  kline_limit: 1000 # Default number of klines to fetch
  cache_exchange_info_ttl_seconds: 3600 # How long to cache exchange info (1 hour)
  cache_klines_ttl_seconds: 60 # How long to cache klines (1 minute) - Adjust based on usage

# Database Configuration
database:
  type: "sqlite" # Or potentially "postgresql" later
  path: "data/db/geminitrader_log.db" # Relative path to the SQLite file

# Logging Configuration
logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_path: "data/logs/trader.log" # Relative path for the main log file
  max_bytes: 10485760 # 10MB max log file size
  backup_count: 5 # Keep 5 backup log files
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Feature Flags (Optional - for enabling/disabling parts of the system)
features:
  enable_live_trading: false # SAFETY FIRST: Keep false initially!
  enable_dca_logic: true
  enable_grid_buying: true
  enable_dynamic_tp: true # Start with dynamic TP based on confidence V1
  enable_news_analysis: false # Phase 4
  enable_orderbook_analysis: false # Phase 5
  enable_influencer_tracking: false # Phase 5
  enable_ml_models: false # Phase 7