# config/config.yaml
# Main configuration file for GeminiTrader

# --- Binance.US API Settings ---
# Credentials should be loaded from .env file (via settings.py)
# Do NOT store keys/secrets directly in this YAML file.
binance_us:
  # api_key: overridden_by_env
  # api_secret: overridden_by_env
  # Optional: API request timeouts, etc.
  # request_timeout: 10

# --- Coinbase API Settings (for funding pipeline) ---
# Credentials should be loaded from .env file
coinbase:
  # api_key: overridden_by_env
  # api_secret: overridden_by_env

# --- Plaid API Settings (Optional, for bank integration) ---
# Credentials should be loaded from .env file
plaid:
  # client_id: overridden_by_env
  # secret: overridden_by_env
  # environment: overridden_by_env (e.g., 'sandbox', 'development', 'production')

# --- Database Settings ---
database:
  # Path relative to project root
  path: data/db
  filename: geminitrader_log.db

# --- Portfolio Settings ---
portfolio:
  # Initial cash balance for backtesting (use Decimal format)
  initial_cash: '10000.00'
  # Target quote asset (e.g., USD, USDT) - Used on Binance.US primarily
  quote_asset: 'USD'

# --- Fee Settings ---
# Fees should be represented as decimals (e.g., 0.001 for 0.1%)
# These are default trading fees, specific pipeline fees might differ.
fees:
  # Maker fee for limit orders on Binance.US
  maker: '0.001'
  # Taker fee for market orders on Binance.US
  taker: '0.001'

# --- Logging Settings ---
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: INFO
  # Path relative to project root for main trader log
  trader_log_path: data/logs/trader.log
  # Path for funding pipeline log
  pipeline_log_path: data/logs/pipeline.log
  # Max log file size in bytes
  max_bytes: 10485760 # 10 MB
  # Number of backup log files to keep
  backup_count: 5

# --- Data Paths ---
# Best Practice: Define standard paths for required data files
data:
  # Path to the primary historical data file used by default for backtesting/analysis
  # Use the fetch_historical_data.py script to create or update this file.
  primary_kline_csv: data/cache/BTCUSD_1h_MAIN.csv
  # Path for caching exchange info (filters)
  exchange_info_cache: data/cache/exchange_info.json

# --- Funding Pipeline Settings ---
# Configuration for transferring funds from Coinbase to Binance.US via a low-fee asset
funding_pipeline:
  # Asset to use for low-fee transfers between exchanges (e.g., XLM, ALGO).
  # NOTE: Dynamic selection based on current fees is a future enhancement (Phase 8+).
  intermediate_asset: 'XLM' # Example: Stellar Lumens
  binance_deposit_address: # Destination addresses on Binance.US - NOT secrets.
    # Address for the INTERMEDIATE asset chosen above
    XLM: "GBUTD5DNV43JBJP7AA657H2CYPUCAAFBXCKX7QE4XXGYIYFZZX2EKKVF"
    # Add other potential intermediate assets if you switch the config later
    # ALGO: "YOUR_BINANCE_US_ALGO_ADDRESS_HERE"
    # Add deposit addresses for primary assets if needed elsewhere
    # BTC: "YOUR_BINANCE_US_BTC_ADDRESS_HERE"
  binance_deposit_memo: # MEMO required for certain assets (e.g., XLM, EOS, ATOM)
    # Ensure you have the correct MEMO for the intermediate asset chosen above
    XLM: "1080077224" # Often a string of numbers
    # ALGO: "" # ALGO typically doesn't use a memo, but check Binance.US

# --- Strategy Settings ---
# Define parameters for different strategy components here
strategies:
  # --- Geometric Grid Strategy (Operates on Binance.US) ---
  geometric_grid:
    base_order_size_usd: '100.00'
    grid_spacing_atr_multiplier: '0.4'
    grid_spacing_geometric_factor: '1.1'
    order_size_geometric_factor: '1.2'
    max_grid_levels: 5
    max_total_grid_quantity_base: '0.5'
    atr_length: 14

  # --- Simple Take Profit Strategy (Operates on Binance.US) ---
  simple_tp:
    tp_method: 'percentage'
    tp_value: '0.015'

  # --- Dollar Cost Averaging (DCA) Strategy ---
  dca:
    # Base amount in QUOTE currency (e.g., USD) for each DCA purchase event.
    # This is the amount intended to be transferred and ultimately used for trading.
    base_amount_usd: '25.00'
    # Schedule for initiating the DCA funding pipeline.
    schedule: 'bi-weekly'
    # (target_asset for final purchase on Binance removed - pipeline focuses on transfer)

# --- Feature Flags (Optional) ---
feature_flags:
  enable_live_trading: false
  enable_dca_pipeline: false
  enable_db_logging: true
  use_confidence_scaling: false

# File path: config/config.yaml